#!/bin/bash

# QUICKSTART - Copia y pega estos comandos para desplegar

echo "🚀 WebStack - Quick Start"
echo "========================"
echo ""
echo "Opción 1: DESPLIEGUE AUTOMÁTICO (recomendado)"
echo "─────────────────────────────────────────────"
echo ""
echo "cd /workspaces/Docker_IAW"
echo "chmod +x scripts/*.sh"
echo "./scripts/deploy.sh"
echo ""
echo "Luego accede a: http://localhost"
echo ""
echo "═════════════════════════════════════════════"
echo ""
echo "Opción 2: DESPLIEGUE MANUAL"
echo "──────────────────────────"
echo ""
echo "cd /workspaces/Docker_IAW"
echo "mkdir -p data backups"
echo "docker-compose build"
echo "docker-compose up -d"
echo ""
echo "Verifica:"
echo "docker-compose ps"
echo "docker-compose logs -f"
echo ""
echo "Accede a: http://localhost"
echo ""
echo "═════════════════════════════════════════════"
echo ""
echo "COMANDOS ÚTILES:"
echo "───────────────"
echo ""
echo "Ver logs en tiempo real:"
echo "  docker-compose logs -f app"
echo "  docker-compose logs -f nginx"
echo ""
echo "Parar servicios:"
echo "  docker-compose stop"
echo ""
echo "Reiniciar:"
echo "  docker-compose restart"
echo ""
echo "Eliminar todo (⚠️ PIERDE DATOS):"
echo "  docker-compose down -v"
echo ""
echo "Hacer backup:"
echo "  ./scripts/backup.sh"
echo ""
echo "Restaurar desde backup:"
echo "  ./scripts/restore.sh /ruta/al/backup.sql.gz"
echo ""
echo "═════════════════════════════════════════════"
echo ""
echo "DOCUMENTACIÓN:"
echo "──────────────"
echo ""
echo "Análisis arquitectura: doc/ARQUITECTURA.md"
echo "Inicio rápido: README.md"
echo "Resumen: RESUMEN_EJECUTIVO.md"
echo "Estructura: ESTRUCTURA_PROYECTO.txt"
echo ""
echo "═════════════════════════════════════════════"
